### ISSUE TITLE
Trabajo para esta semana

### ISSUE THREAD

**Issue by alejandroleon98** [Arquisoft/viade_es2a#53]
- [x] separar en componentes lo de ver ruta comentarios y imagenes en dos componentes diferentes

- [x] crear un componente con la parte de ficheros de route-element (error al hacerlo por los modales)

- [x] children dentro del container (igual que en el componente rutas y en el feed)
	- comentarios 	(que se refieren a un punto y tienen fecha) (dependencia que se usa para poner 
           hace cuanto tiempo. esta para las rutas. se llama moment. esta en children de app-route)
	- multimedia

- [x] poder tener ni comentarios ni multimedia selecionados, para ver mas grande el mapa.

- [x] al comentar, que se borre el texto que ya hay, 

- [x] y que se resete el punto. (con un estado)

- [x] autorid se quita no hace falta.

- [x] elegir punto de un comentario
	- sacar modal con radio-button que deje escojer un punto, con sus colores
	- el simbolo de elegir punto tiene que tener el color del punto que eliges
	- en el json a generar poner el punto selecionado

para el color:
marker coje el simbolo 0.svg. cojemos el 'id'.svg.
cuando no tienes seleccionado nada ponemos uno gris, o blanco, vacio.

ejemplo de json que genera un comentario:
{
	content: "buena ruta"
	date: Date.now()
	waypoint: el indice del waypoint (los que tienen los colores)
}

Ojo! Un comentario no tiene autor, porque el comentario esta almacenado en el pod del autor.

No olvidarse de hacer documentación y TESTs

**Comment by uo252137** [comment]
Problema con los hooks al separar un componente con las tabs. Revisar el miercoles.
