### ISSUE TITLE
Problemas en Grupos

### ISSUE THREAD

**Issue by tangotelli** [Arquisoft/viade_es2a#75]
- Cuando el grupo tiene más de 2 miembros, el contenido del modal rebasa los bordes. Además, el modal no se muestra de la forma que debería. Revisar CSS.

- Eliminación de grupos sin implementar.

**Comment by UO265180** [comment]
#73

**Comment by tangotelli** [comment]
El commit 7da4d1f de la rama grupos termina de solucionar todos estos problemas.
