### ISSUE TITLE
Formulario de crear rutas se borra al cambiar a multimedia.

### ISSUE THREAD

**Issue by uo265363** [Arquisoft/viade_es2a#91]
SI se escribe en los datos de la ruta al crearla, si se cambia a la ventana de multimedia se borra lo escrito previamente en la ventana de datos.

**Comment by alejandroleon98** [comment]
Lo arregle cambiando el if (selectedTab) se muestra uno : se muestra otro, por un atributo hidden que es selectedTab en uno y !selectedTab en otro, y false si selectedTab es null. Así no se tiene que crear de nuevo el componente
